Update Prospector config, fix CI, checks
deskew/__init__.py:4:40: F401(ruff): `typing.Optional` imported but unused [See: https://docs.astral.sh/ruff/rules/unused-import]
deskew/__init__.py:343:9: B028(ruff): No explicit `stacklevel` keyword argument found [See: https://docs.astral.sh/ruff/rules/no-explicit-stacklevel]

deskew/__init__.py:44:16: error(mypy): Call to untyped function "rgba2rgb" in typed context  [no-untyped-call]
deskew/__init__.py:46:13: error(mypy): Call to untyped function "canny" in typed context  [no-untyped-call]
deskew/__init__.py:47:30: error(mypy): Call to untyped function "hough_line" in typed context  [no-untyped-call]
deskew/__init__.py:50:35: error(mypy): Call to untyped function "hough_line_peaks" in typed context  [no-untyped-call]
************* Module deskew.cli
deskew/cli.py:48:23: error(mypy): Call to untyped function "rotate" in typed context  [no-untyped-call]
deskew/cli.py:55:23: error(mypy): Call to untyped function "rotate" in typed context  [no-untyped-call]